version: '2'
services:
  shopdigi-app:
    image: shopdigi
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shopdigi-postgresql:5432/shopdigi
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://shopdigi-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://shopdigi-elasticsearch:9200
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - 8080:8080
  shopdigi-postgresql:
    extends:
      file: postgresql.yml
      service: shopdigi-postgresql
  shopdigi-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: shopdigi-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
